Adiciona breve descrição no README do projeto (#5)
rohanaceres/tcc pull request #15
Opened 2017-10-20 18:40 UTC by rohanaceres

2017-10-20 19:08 UTC, thaynaracsantos requested changes

2017-10-20 19:08 UTC, ThaynaraSantos commented on README.md
> +Esta pesquisa utilizará o método dedutivo, desenvolvendo cadeias de raciocínio com premissas bem definidas para chegar a uma conclusão clara e objetiva. Além disso, este trabalho consiste em uma pesq
Fiz algumas alterações nesse texto para solução proposta, compara com ele por favor.

2017-10-20 23:18 UTC, rohanaceres commented on README.md
> +Esta pesquisa utilizará o método dedutivo, desenvolvendo cadeias de raciocínio com premissas bem definidas para chegar a uma conclusão clara e objetiva. Além disso, este trabalho consiste em uma pesq
Ué, você tirou a parte da metodologia?

2017-10-21 02:55 UTC, ThaynaraSantos commented on README.md
> +Esta pesquisa utilizará o método dedutivo, desenvolvendo cadeias de raciocínio com premissas bem definidas para chegar a uma conclusão clara e objetiva. Além disso, este trabalho consiste em uma pesq
Só da introdução, se não iria ficar repetido.

2017-10-21 13:06 UTC, rohanaceres commented on README.md
> +Esta pesquisa utilizará o método dedutivo, desenvolvendo cadeias de raciocínio com premissas bem definidas para chegar a uma conclusão clara e objetiva. Além disso, este trabalho consiste em uma pesq
okayyyy!

2017-10-21 13:10 UTC, rohanaceres commented on README.md
> +Esta pesquisa utilizará o método dedutivo, desenvolvendo cadeias de raciocínio com premissas bem definidas para chegar a uma conclusão clara e objetiva. Além disso, este trabalho consiste em uma pesq
Feito no comia 09c34df7d6e2d10c7e6b89e0cc5fbf8fca2a91af

2017-10-21 13:18 UTC, thaynaracsantos approved these changes

2017-10-21 13:19 UTC, merged