#2 Breve resumo histórico e estado da arte
rohanaceres/tcc pull request #7
Opened 2017-10-17 05:19 UTC by ThaynaraSantos

Breve resumo histórico

O contexto que originou o problema que o TCC está se propondo a resolver/mitigar.

Pesquisas de medição da poluição
Uso de transporte alternativo
Estado da arte

Tecnologias atuais; contexto atual sendo utilizado para resolver/mitigar o problema proposto.

4 parágrafos por paper. Pesquisar no google academics e resumir o abstract, introduction e conclusion de cada paper. Colocar o link de cada um aqui na issue.
3 papers de 2017
2 papers de 2016
1 paper de 2015

2017-10-18 00:55 UTC, rohanaceres requested changes
Não li o trabalho inteiro, porque já fiz 32 comentários e claramente você copiou a tradução direto aqui. Revisa esse texto e manda de novo.

2017-10-18 00:55 UTC, rohanaceres commented on chapters/chapter2-historical-summary.md
> +...
O que é isso?

2017-10-18 00:55 UTC, rohanaceres commented on chapters/chapter2-historical-summary.md
> +A poluição do ar é uma importante preocupação de saúde pública, especialmente para crianças particularmente suscetíveis. A América Latina tem uma grande população infantil, é altamente urbanizada e o
No finalzinho ficou confuso, porque parece que o Chile é uma cidade, e ficam 5 cidades, não 4 como diz o texto.

2017-10-18 00:55 UTC, rohanaceres commented on chapters/chapter2-historical-summary.md
> +Os modelos de aditivos generalizados na regressão de Poisson foram utilizados para ajustar as séries temporais diárias de mortalidade por doenças respiratórias em lactentes e crianças e níveis de PM1
O que seria "estimativa de resumo"?

2017-10-18 00:55 UTC, rohanaceres commented on chapters/chapter2-historical-summary.md
> +Essas cidades recebem quase 43 milhões de pessoas e os níveis de poluição estavam acima das diretrizes da OMS. Para PM10, o aumento percentual do risco de morte devido a doenças respiratórias em lact
O que é "(0,09-0,85)", "(0,08-1,08)" e "(0,91-1,85)"?

2017-10-18 00:55 UTC, rohanaceres commented on chapters/chapter2-historical-summary.md
> +Essas cidades recebem quase 43 milhões de pessoas e os níveis de poluição estavam acima das diretrizes da OMS. Para PM10, o aumento percentual do risco de morte devido a doenças respiratórias em lact
Trocar "crianças de 1-5 anos" por "crianças de 1 à 5 anos".

2017-10-18 00:55 UTC, rohanaceres commented on chapters/chapter2-historical-summary.md
> +Essas cidades recebem quase 43 milhões de pessoas e os níveis de poluição estavam acima das diretrizes da OMS. Para PM10, o aumento percentual do risco de morte devido a doenças respiratórias em lact
Trocar "crianças de 1 a 14 anos" por "crianças de 1 à 14 anos".

2017-10-18 00:55 UTC, rohanaceres commented on chapters/chapter2-historical-summary.md
> +Essas cidades recebem quase 43 milhões de pessoas e os níveis de poluição estavam acima das diretrizes da OMS. Para PM10, o aumento percentual do risco de morte devido a doenças respiratórias em lact
"[1,38% (0,91-1,85). )]", essa parte está bem ruim. É um documento, não uma fórmula matemática...

2017-10-18 00:55 UTC, rohanaceres commented on chapters/chapter2-historical-summary.md
> +Essas cidades recebem quase 43 milhões de pessoas e os níveis de poluição estavam acima das diretrizes da OMS. Para PM10, o aumento percentual do risco de morte devido a doenças respiratórias em lact
"na estação quente" seria "no verão"?

2017-10-18 00:55 UTC, rohanaceres commented on chapters/chapter2-historical-summary.md
> +Essas cidades recebem quase 43 milhões de pessoas e os níveis de poluição estavam acima das diretrizes da OMS. Para PM10, o aumento percentual do risco de morte devido a doenças respiratórias em lact
"enquanto os efeitos negativos foram observados para as mortes respiratórias e LRI em crianças." ??????????????????????????????????

2017-10-18 00:55 UTC, rohanaceres commented on chapters/chapter2-historical-summary.md
> +Foram verificadas estimativas de impacto de mortalidade comparáveis de poluentes atmosféricos em todas essas cidades e grupos etários. Esta informação é importante porque muitas políticas públicas de
O que significa "mortalidade comparáveis"?

2017-10-18 00:55 UTC, rohanaceres commented on chapters/chapter2-historical-summary.md
> +Três bicicletas instrumentadas foram usadas para medir as concentrações de carbono preto (BC) e PM2.5 em uma cidade de médio porte no sul do Brasil. O objetivo deste estudo foi mapear a distribuição
Trocar "p.ex" por "por exemplo".

2017-10-18 00:55 UTC, rohanaceres commented on chapters/chapter2-historical-summary.md
> +Esses resultados implicam que ônibus antigos e caminhões diesel podem ser o principal motor de trás dos altos níveis de poluição no núcleo interno da cidade. Observamos uma forte relação entre as con
"motor de trás"?

2017-10-18 00:55 UTC, rohanaceres commented on chapters/chapter2-historical-summary.md
> +Esses resultados implicam que ônibus antigos e caminhões diesel podem ser o principal motor de trás dos altos níveis de poluição no núcleo interno da cidade. Observamos uma forte relação entre as con
"HDDV> 100 veículos h-1"?

2017-10-18 00:55 UTC, rohanaceres commented on chapters/chapter2-historical-summary.md
> +Esses resultados implicam que ônibus antigos e caminhões diesel podem ser o principal motor de trás dos altos níveis de poluição no núcleo interno da cidade. Observamos uma forte relação entre as con
Ficou um 'a' a mais em "atribuído a a maior".

2017-10-18 00:55 UTC, rohanaceres commented on chapters/chapter2-historical-summary.md
> +### Efeitos do veículo em movimento acende na dispersão de poluentes dentro de um túnel rodoviário - (Novembro 2016)
"acende"?

2017-10-18 00:55 UTC, rohanaceres commented on chapters/chapter2-historical-summary.md
> +Este estudo investiga a dispersão de poluentes em um túnel rodoviário na presença de veículo em movimento por uma abordagem de velocidade relativa usando CFD 3-D (Dinâmica de fluido computacional de
Faltou uma vírgula antes do "por".

2017-10-18 00:55 UTC, rohanaceres commented on chapters/chapter2-historical-summary.md
> +O comportamento turbulento do fluxo de ar em torno de veículos de diferentes formas e seu impacto na dispersão de poluentes foram estudados. As geometrias do veículo de diferentes formas foram extraí
"literatura de pressão estática"?

2017-10-18 00:55 UTC, rohanaceres commented on chapters/chapter2-historical-summary.md
> +O comportamento turbulento do fluxo de ar em torno de veículos de diferentes formas e seu impacto na dispersão de poluentes foram estudados. As geometrias do veículo de diferentes formas foram extraí
Faltou uma virgula antes do "e validado com".

2017-10-18 00:55 UTC, rohanaceres commented on chapters/chapter2-historical-summary.md
> +Os resultados mostraram que os acordes variaram com o tamanho, a forma e a velocidade dos veículos. O fluxo de tráfego misturado produziu acordes mais altas do campo próximo e acelerou o efeito do pi
"acordes"?

2017-10-18 00:55 UTC, rohanaceres commented on chapters/chapter2-historical-summary.md
> +Os transportes públicos, como trens atuais, metrôs, VLTs (Veículo Leve sobre Trilhos) são movidos através de recursos renováveis como, no caso do Brasil, energia hidrelétrica, tem um papel importante
O que são " trens atuais"?

2017-10-18 00:55 UTC, rohanaceres commented on chapters/chapter2-historical-summary.md
> +Os transportes públicos, como trens atuais, metrôs, VLTs (Veículo Leve sobre Trilhos) são movidos através de recursos renováveis como, no caso do Brasil, energia hidrelétrica, tem um papel importante
Trocar "tem um papel importante" por "têm um papel importante"

2017-10-18 00:55 UTC, rohanaceres commented on chapters/chapter2-historical-summary.md
> +Além do trasporte público, outro meio de transporte sustentável que tem ganhado cada vez mais força como meio de transporte alternativo são as bicicletas, em alguns países como Índia, Noruega, Colomb
Faltou um ponto final depois de "são as bicicletas".

2017-10-18 00:55 UTC, rohanaceres commented on chapters/chapter2-historical-summary.md
> +Além do trasporte público, outro meio de transporte sustentável que tem ganhado cada vez mais força como meio de transporte alternativo são as bicicletas, em alguns países como Índia, Noruega, Colomb
prática*

2017-10-18 00:55 UTC, rohanaceres commented on chapters/chapter2-historical-summary.md
> +Países como Holanda, considerada capital mundial da bicicleta, e Dinamarca tem o maior investimento em infraestrutura e cultura *bike-friendly*, oferencendo aulas sobre o uso de bicicletas nas escola
têm*

2017-10-18 00:55 UTC, rohanaceres commented on chapters/chapter2-historical-summary.md
> +No Brasil, mais especificamente no Rio de Janeiro, o programa *Rio - Estado da Bicicleta* tem como objetivo incentivar o uso da bicicleta como meio de transporte nas cidades, criado pela Secretaria d
meios de transporte*

2017-10-18 00:55 UTC, rohanaceres commented on chapters/chapter2-historical-summary.md
> +Em relação a poluição do ar, as pesquisas comprovaram que ciclistas são mais suscetíveis a inalar maiores doses de NO2 (dióxido de nitrogénio), mas ainda existem outros tipos de substâncias que devem
Em relação à poluição*

2017-10-18 00:55 UTC, rohanaceres commented on chapters/chapter2-historical-summary.md
> +O estado da arte é um momento importante do documento, pois mostra as pesquisas mais recentes e relevantes, que foram desenvolvidas, relacionadas ao tema, dando um ponto de partida para o projeto, lo
Não consegui entender esse parágrafo...

2017-10-18 00:55 UTC, rohanaceres commented on chapters/chapter2-historical-summary.md
> +## Hotspots de emissões urbanas: Quantificando o congestionamento do veículo e a poluição do ar usando dados de GPS do telefone celular - (Outubro 2017)
quantificando*

Depois de dois pontos, a letra é minúscula.

2017-10-18 00:55 UTC, rohanaceres commented on chapters/chapter2-historical-summary.md
> +Para isso, foi construído um inventário altamente resolvido de fluxos horários de CO, NO2, NOx, PM2.5 e CO2 de veículos rodoviários em 280.000 segmentos rodoviários no leste de Massachusetts para o a
O que são "velocidades horárias do veículo"?

2017-10-18 00:55 UTC, rohanaceres commented on chapters/chapter2-historical-summary.md
> +Para isso, foi construído um inventário altamente resolvido de fluxos horários de CO, NO2, NOx, PM2.5 e CO2 de veículos rodoviários em 280.000 segmentos rodoviários no leste de Massachusetts para o a
O que são "corredores chave"?

2017-10-18 00:55 UTC, rohanaceres commented on chapters/chapter2-historical-summary.md
> +Para isso, foi construído um inventário altamente resolvido de fluxos horários de CO, NO2, NOx, PM2.5 e CO2 de veículos rodoviários em 280.000 segmentos rodoviários no leste de Massachusetts para o a
O que são "condições não conjugadas"?

2017-10-18 00:55 UTC, rohanaceres commented on chapters/chapter2-historical-summary.md
> +Para isso, foi construído um inventário altamente resolvido de fluxos horários de CO, NO2, NOx, PM2.5 e CO2 de veículos rodoviários em 280.000 segmentos rodoviários no leste de Massachusetts para o a
"as emissões de CO concordam dentro de 5% para os dois inventários"?

2017-10-18 01:55 UTC, ThaynaraSantos commented on chapters/chapter2-historical-summary.md
> +A poluição do ar é uma importante preocupação de saúde pública, especialmente para crianças particularmente suscetíveis. A América Latina tem uma grande população infantil, é altamente urbanizada e o
Ok, quatro cidades, sendo Santiago no Chile.

2017-10-18 01:56 UTC, ThaynaraSantos commented on chapters/chapter2-historical-summary.md
> +Os modelos de aditivos generalizados na regressão de Poisson foram utilizados para ajustar as séries temporais diárias de mortalidade por doenças respiratórias em lactentes e crianças e níveis de PM1
Era pra ser só estimativa mesmo.

2017-10-18 01:56 UTC, ThaynaraSantos commented on chapters/chapter2-historical-summary.md
> +Essas cidades recebem quase 43 milhões de pessoas e os níveis de poluição estavam acima das diretrizes da OMS. Para PM10, o aumento percentual do risco de morte devido a doenças respiratórias em lact
Os indices do modelo de regresão linear, mas vou deixar só com %.

2017-10-18 01:58 UTC, ThaynaraSantos commented on chapters/chapter2-historical-summary.md
> +Essas cidades recebem quase 43 milhões de pessoas e os níveis de poluição estavam acima das diretrizes da OMS. Para PM10, o aumento percentual do risco de morte devido a doenças respiratórias em lact
Ok

2017-10-18 01:58 UTC, ThaynaraSantos commented on chapters/chapter2-historical-summary.md
> +Essas cidades recebem quase 43 milhões de pessoas e os níveis de poluição estavam acima das diretrizes da OMS. Para PM10, o aumento percentual do risco de morte devido a doenças respiratórias em lact
Ok

2017-10-18 01:59 UTC, ThaynaraSantos commented on chapters/chapter2-historical-summary.md
> +Essas cidades recebem quase 43 milhões de pessoas e os níveis de poluição estavam acima das diretrizes da OMS. Para PM10, o aumento percentual do risco de morte devido a doenças respiratórias em lact
Ok

2017-10-18 02:00 UTC, ThaynaraSantos commented on chapters/chapter2-historical-summary.md
> +Essas cidades recebem quase 43 milhões de pessoas e os níveis de poluição estavam acima das diretrizes da OMS. Para PM10, o aumento percentual do risco de morte devido a doenças respiratórias em lact
Trocado.

2017-10-18 02:09 UTC, ThaynaraSantos commented on chapters/chapter2-historical-summary.md
> +Essas cidades recebem quase 43 milhões de pessoas e os níveis de poluição estavam acima das diretrizes da OMS. Para PM10, o aumento percentual do risco de morte devido a doenças respiratórias em lact
Foi citado antes, infecções respiratórias inferiores (LRI), LRI é a sigla em inglês para 
lower respiratory infections. 

A mesma coisa que você fez na introdução com AIDs (síndrome da imunodeficiência adquirida) pela mesma lógica deveria ter colocado SIDA.

Corrijo aqui para IRI e você vai corrigir lá para SIDA?

2017-10-18 02:13 UTC, ThaynaraSantos commented on chapters/chapter2-historical-summary.md
> +Foram verificadas estimativas de impacto de mortalidade comparáveis de poluentes atmosféricos em todas essas cidades e grupos etários. Esta informação é importante porque muitas políticas públicas de
Corrigido para "estimativas, de mortalidade, em relação ao impacto dos poluentes atmosféricos"

2017-10-18 02:14 UTC, ThaynaraSantos commented on chapters/chapter2-historical-summary.md
> +Três bicicletas instrumentadas foram usadas para medir as concentrações de carbono preto (BC) e PM2.5 em uma cidade de médio porte no sul do Brasil. O objetivo deste estudo foi mapear a distribuição
Ok

2017-10-18 02:14 UTC, ThaynaraSantos commented on chapters/chapter2-historical-summary.md
> +Esses resultados implicam que ônibus antigos e caminhões diesel podem ser o principal motor de trás dos altos níveis de poluição no núcleo interno da cidade. Observamos uma forte relação entre as con
Corrigido para "os principais agentes"

2017-10-18 02:22 UTC, ThaynaraSantos commented on chapters/chapter2-historical-summary.md
> +Esses resultados implicam que ônibus antigos e caminhões diesel podem ser o principal motor de trás dos altos níveis de poluição no núcleo interno da cidade. Observamos uma forte relação entre as con
Foi citado antes, número de veículos diesel pesados (HDDV). Mesma situação do LRI e AIDs. 
h-1 acredito que seja em relação a inclinação, high - 1.
Mas vou tirar essas partes de h-1 e m-3.

2017-10-18 02:22 UTC, ThaynaraSantos commented on chapters/chapter2-historical-summary.md
> +Esses resultados implicam que ônibus antigos e caminhões diesel podem ser o principal motor de trás dos altos níveis de poluição no núcleo interno da cidade. Observamos uma forte relação entre as con
Corrigido

2017-10-18 02:23 UTC, ThaynaraSantos commented on chapters/chapter2-historical-summary.md
> +### Efeitos do veículo em movimento acende na dispersão de poluentes dentro de um túnel rodoviário - (Novembro 2016)
Era pra ser aumenta.

2017-10-18 02:24 UTC, ThaynaraSantos commented on chapters/chapter2-historical-summary.md
> +Este estudo investiga a dispersão de poluentes em um túnel rodoviário na presença de veículo em movimento por uma abordagem de velocidade relativa usando CFD 3-D (Dinâmica de fluido computacional de
Ok

2017-10-18 02:24 UTC, ThaynaraSantos commented on chapters/chapter2-historical-summary.md
> +O comportamento turbulento do fluxo de ar em torno de veículos de diferentes formas e seu impacto na dispersão de poluentes foram estudados. As geometrias do veículo de diferentes formas foram extraí
Era pra ser leitura.

2017-10-18 02:25 UTC, ThaynaraSantos commented on chapters/chapter2-historical-summary.md
> +O comportamento turbulento do fluxo de ar em torno de veículos de diferentes formas e seu impacto na dispersão de poluentes foram estudados. As geometrias do veículo de diferentes formas foram extraí
Ok.

2017-10-18 02:31 UTC, ThaynaraSantos commented on chapters/chapter2-historical-summary.md
> +Os resultados mostraram que os acordes variaram com o tamanho, a forma e a velocidade dos veículos. O fluxo de tráfego misturado produziu acordes mais altas do campo próximo e acelerou o efeito do pi
Estava sem ideia de palavras, achei que nuance ficaria mais estranho, mas agora troquei por aumentos e dispersão.

2017-10-18 02:35 UTC, ThaynaraSantos commented on chapters/chapter2-historical-summary.md
> +Os transportes públicos, como trens atuais, metrôs, VLTs (Veículo Leve sobre Trilhos) são movidos através de recursos renováveis como, no caso do Brasil, energia hidrelétrica, tem um papel importante
Os que não são maria fumaça, tem cidades que ainda utilizam os trens antigos. Não me veio a mente outro termo mais apropriado, também achei que tren elétrico iria ficar estranho, mas vou mudar pra esse.

2017-10-18 02:36 UTC, ThaynaraSantos commented on chapters/chapter2-historical-summary.md
> +Os transportes públicos, como trens atuais, metrôs, VLTs (Veículo Leve sobre Trilhos) são movidos através de recursos renováveis como, no caso do Brasil, energia hidrelétrica, tem um papel importante
Ok

2017-10-18 02:41 UTC, ThaynaraSantos commented on chapters/chapter2-historical-summary.md
> +Além do trasporte público, outro meio de transporte sustentável que tem ganhado cada vez mais força como meio de transporte alternativo são as bicicletas, em alguns países como Índia, Noruega, Colomb
Essa parte ficou ruim. Corrigido.

2017-10-18 02:42 UTC, ThaynaraSantos commented on chapters/chapter2-historical-summary.md
> +Além do trasporte público, outro meio de transporte sustentável que tem ganhado cada vez mais força como meio de transporte alternativo são as bicicletas, em alguns países como Índia, Noruega, Colomb
Ok.

2017-10-18 02:42 UTC, ThaynaraSantos commented on chapters/chapter2-historical-summary.md
> +Países como Holanda, considerada capital mundial da bicicleta, e Dinamarca tem o maior investimento em infraestrutura e cultura *bike-friendly*, oferencendo aulas sobre o uso de bicicletas nas escola
Ok.

2017-10-18 02:43 UTC, ThaynaraSantos commented on chapters/chapter2-historical-summary.md
> +No Brasil, mais especificamente no Rio de Janeiro, o programa *Rio - Estado da Bicicleta* tem como objetivo incentivar o uso da bicicleta como meio de transporte nas cidades, criado pela Secretaria d
Ok.

2017-10-18 02:43 UTC, ThaynaraSantos commented on chapters/chapter2-historical-summary.md
> +Em relação a poluição do ar, as pesquisas comprovaram que ciclistas são mais suscetíveis a inalar maiores doses de NO2 (dióxido de nitrogénio), mas ainda existem outros tipos de substâncias que devem
Ok

2017-10-18 02:48 UTC, ThaynaraSantos commented on chapters/chapter2-historical-summary.md
> +O estado da arte é um momento importante do documento, pois mostra as pesquisas mais recentes e relevantes, que foram desenvolvidas, relacionadas ao tema, dando um ponto de partida para o projeto, lo
Ficou meio confuso mesmo.

2017-10-18 02:50 UTC, ThaynaraSantos commented on chapters/chapter2-historical-summary.md
> +## Hotspots de emissões urbanas: Quantificando o congestionamento do veículo e a poluição do ar usando dados de GPS do telefone celular - (Outubro 2017)
Ok

2017-10-18 02:52 UTC, ThaynaraSantos commented on chapters/chapter2-historical-summary.md
> +Para isso, foi construído um inventário altamente resolvido de fluxos horários de CO, NO2, NOx, PM2.5 e CO2 de veículos rodoviários em 280.000 segmentos rodoviários no leste de Massachusetts para o a
Deve ser velocidade crescente.

2017-10-18 02:53 UTC, ThaynaraSantos commented on chapters/chapter2-historical-summary.md
> +Para isso, foi construído um inventário altamente resolvido de fluxos horários de CO, NO2, NOx, PM2.5 e CO2 de veículos rodoviários em 280.000 segmentos rodoviários no leste de Massachusetts para o a
Deve ser pontos extratégicos.

2017-10-18 03:00 UTC, ThaynaraSantos commented on chapters/chapter2-historical-summary.md
> +Para isso, foi construído um inventário altamente resolvido de fluxos horários de CO, NO2, NOx, PM2.5 e CO2 de veículos rodoviários em 280.000 segmentos rodoviários no leste de Massachusetts para o a
Deve ser "não verificadas"

2017-10-18 03:04 UTC, ThaynaraSantos commented on chapters/chapter2-historical-summary.md
> +Para isso, foi construído um inventário altamente resolvido de fluxos horários de CO, NO2, NOx, PM2.5 e CO2 de veículos rodoviários em 280.000 segmentos rodoviários no leste de Massachusetts para o a
As emissões de CO tem 5% de emissões agregadas tanto no Inventário Nacional de Emissões (NEI) quanto no resultado do inventário da pesquisa.

A dúvida foi em relação a que?

2017-10-18 03:08 UTC, ThaynaraSantos commented on chapters/chapter2-historical-summary.md
> +...
Que além de fatores como faixa etária, região, alimentação e etc, que são sempre levados em consideração em experimentos, também é importante levar em consideração as atividades físicas de cada indivíduo, pois esses também influenciam nas doses de substâncias inaladas, e conforme o estudo, isso pode ser feito com precisão através do GPS e acelerômetro.

2017-10-18 03:47 UTC, ThaynaraSantos commented
"Não li o trabalho inteiro, porque já fiz 32 comentários e claramente você copiou a tradução direto aqui. Revisa esse texto e manda de novo."

Pior que não, em relação aos artigos (que foram explicitamente citados) eu li e li de novo, reescrevi algumas partes, mas algumas coisas infelizmente eu deixei passar. O restante eu escrevi do zero, mas obrigada pela revisão! Depois, se possível, responda as questões que ficaram em aberto, por favor.

2017-10-19 18:05 UTC, rohanaceres approved these changes
Fiz algumas mudanças. Dá uma olhada.

2017-10-19 18:05 UTC, rohanaceres commented on chapters/chapter2-historical-summary.md
> +O comportamento turbulento do fluxo de ar em torno de veículos de diferentes formas e seu impacto na dispersão de poluentes foram estudados. As geometrias do veículo de diferentes formas foram extraí
Achei esse e o próximo parágrafos muito confusos. Dei uma olhada no paper e vi que o vocabulário é muito técnico, e não consegui achar de quais trechos você tirou esses parágrafos. Vamos nos reunir quando der pra tentarmos fazer juntas essa parte, acho que vai ser mais produtivo.

2017-10-19 18:19 UTC, ThaynaraSantos commented on chapters/chapter2-historical-summary.md
> +O comportamento turbulento do fluxo de ar em torno de veículos de diferentes formas e seu impacto na dispersão de poluentes foram estudados. As geometrias do veículo de diferentes formas foram extraí
Ok, mas pelo que eu entendi, esse trecho fala que eles fizeram o estudo com base nos modelos gerados, e para verificar se os modelos eram válidos eles usaram dados de experimentos reais com carros em movimento.

2017-10-19 18:25 UTC, merged